#!/usr/bin/env python3
"""AI Work-per-Dollar Index.

Ranks curated subscription rows (model x thinking level x plan) by
intelligence-weighted benchmark work per dollar:

    monthly tokens = price_usd / real_usd_per_mtok * 1e6
    tasks/month    = monthly tokens / tok_per_task
    value          = score * tasks/month / price_usd

Input (data/pricing_gen.csv): generated by fetch_pricing.py, which already
curates the repo data and merges in the hand-maintained
data/pricing_extra.csv overrides (edit that file, then re-run fetch_pricing.py).
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
PRICING_CSV = DATA_DIR / "pricing_gen.csv"

# ---------------------------------------------------------------------------
# ANSI styling
# ---------------------------------------------------------------------------

ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")
USE_COLOR = sys.stdout.isatty() and not os.environ.get("NO_COLOR")


def paint(text: str, *codes: str) -> str:
    if not USE_COLOR or not codes:
        return text
    return f"\x1b[{';'.join(codes)}m{text}\x1b[0m"


def vlen(text: str) -> int:
    return len(ANSI_RE.sub("", text))


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def read_rows(path: Path) -> list[dict]:
    with open(path, newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def load_pricing_rows() -> tuple[list[dict], int]:
    """Returns (rows, malformed)."""
    rows, malformed = [], 0
    for row in read_rows(PRICING_CSV):
        try:
            fee = float(row["price_usd"])
            real_price = float(row["real_usd_per_mtok"])
            score = float(row["score"])
            tok_per_task = int(row["tok_per_task"])
        except ValueError:
            malformed += 1
            continue
        monthly_tokens = fee / real_price * 1e6
        rows.append({
            "id": row["id"],
            "model": row["model"],
            "effort": row["effort"],
            "plan": row["plan"],
            "fee": fee,
            "monthly_tokens": monthly_tokens,
            "score": score,
            "tpt": tok_per_task,
        })
    return rows, malformed


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def nonneg_float(value: str) -> float:
    try:
        number = float(value)
    except ValueError:
        raise argparse.ArgumentTypeError(f"{value!r} is not a number")
    if number < 0:
        raise argparse.ArgumentTypeError("must be >= 0")
    return number


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rank subscription plans by intelligence-weighted benchmark work per dollar.")
    parser.add_argument("--min-tasks", type=nonneg_float, default=0.0, metavar="N",
                        help="hide results providing fewer than N tasks/month (default: no limit)")
    parser.add_argument("--min-score", type=nonneg_float, default=0.0, metavar="N",
                        help="hide results with an AA intelligence score below N (default: no limit)")
    parser.add_argument("--max-price", type=nonneg_float, default=0.0, metavar="N",
                        help="hide results costing more than N per month (default: no limit)")
    return parser.parse_args(argv)


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

HEADERS = ["Rank", "Model", "Effort", "Plan", "Price/mo", "Score", "Tok/task", "Tasks/month", "Value"]
ALIGNS = ["r", "l", "l", "l", "r", "r", "r", "r", "r"]


def render_row(cells, widths, color_codes=None):
    parts = []
    for i, cell in enumerate(cells):
        padded = cell.rjust(widths[i]) if ALIGNS[i] == "r" else cell.ljust(widths[i])
        parts.append(paint(padded, *color_codes) if color_codes else padded)
    return "  ".join(parts)


def main(argv=None) -> int:
    args = parse_args(argv)

    if not PRICING_CSV.exists():
        print(paint(f"Missing input file: {PRICING_CSV.name} (run fetch_pricing.py first)", "31", "1"))
        return 1

    rows, malformed = load_pricing_rows()

    ranked = []
    for r in rows:
        tasks_month = r["monthly_tokens"] / r["tpt"]
        tasks_per_dollar = tasks_month / r["fee"]
        ranked.append({**r,
                       "tasks_month": tasks_month,
                       "tasks_per_dollar": tasks_per_dollar,
                       "value": r["score"] * tasks_per_dollar})

    filter_notes = []
    if args.min_tasks > 0:
        before = len(ranked)
        ranked = [r for r in ranked if r["tasks_month"] >= args.min_tasks]
        filter_notes.append(
            f"--min-tasks: hid {before - len(ranked)} of {before} results below {args.min_tasks:,.10g} tasks/month")
    if args.min_score > 0:
        before = len(ranked)
        ranked = [r for r in ranked if r["score"] >= args.min_score]
        filter_notes.append(
            f"--min-score: hid {before - len(ranked)} of {before} results below {args.min_score:g} score")
    if args.max_price > 0:
        before = len(ranked)
        ranked = [r for r in ranked if r["fee"] <= args.max_price]
        filter_notes.append(
            f"--max-price: hid {before - len(ranked)} of {before} results above ${args.max_price:g}/month")

    ranked.sort(key=lambda r: r["value"], reverse=True)

    if not ranked:
        print(paint("No results remain after filtering.", "33", "1"))
        print()
        return 0

    print()
    print(paint("AI Work-per-Dollar Index", "1"))
    print(paint("Intelligence-weighted benchmark tasks per USD — model × thinking level × plan", "2"))
    print()

    table = []
    for i, r in enumerate(ranked, 1):
        table.append([
            str(i),
            r["model"],
            "—" if r["effort"] == "none" else r["effort"],
            r["plan"],
            f"${r['fee']:g}",
            f"{r['score']:.2f}",
            f"{r['tpt']:,}",
            f"{r['tasks_month']:,.0f}",
            f"{r['value']:,.0f}",
        ])

    widths = [vlen(h) for h in HEADERS]
    for row in table:
        for i, cell in enumerate(row):
            widths[i] = max(widths[i], vlen(cell))

    print(render_row(HEADERS, widths, ("1", "36")))
    print(paint("─" * (sum(widths) + 2 * (len(widths) - 1)), "2"))
    for i, row in enumerate(table, 1):
        if i == 1:
            print(render_row(row, widths, ("1", "32")))
        elif i <= 3:
            print(render_row(row, widths, ("32",)))
        else:
            print(render_row(row, widths))

    print()
    print(paint("value = AA intelligence score × (monthly tokens ÷ tok_per_task) ÷ price_usd", "2"))
    print(paint("monthly tokens = price_usd ÷ real_usd_per_mtok × 1,000,000", "2"))
    print(paint("tok_per_task = answer + reasoning tokens per AA Intelligence Index task (data/aa_tok_per_task.csv)", "2"))
    print(paint('"—" thinking level = the provider exposes no effort selector (default config; max assumed)', "2"))

    if malformed:
        print(paint(f"skipped {malformed} malformed rows", "33"))
    for note in filter_notes:
        print(paint(note, "33"))
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
